app_profile/urls.py
from django.conf.urls import url
from .views import index, stats, add_friend, add_status, edit_profile

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
    url(r'^home/$', stats, name='stats'),
    url(r'^add_status', add_status, name='add_status'),

    url(r'^mahasiswa/$', stats, name='stats'),
    url(r'^mahasiswa/profile/edit$', edit_profile, name='edit_profile'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import app_profile.urls as app

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(app, namespace='app')),
]

app_profile/models.py
from django.db import models
import datetime

YEAR_CHOICES = []
for r in range(1900, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))

LEVEL_CHOICES = (
	('',''),
	('Beginner','Beginner'),
	('Intermediate','Intermediate'),
	('Advanced','Advanced'),
	('Expert','Expert'),
	('Legend','Legend'),
)

class Teman(models.Model):
	NPM = models.CharField(max_length=10)
	Nama = models.TextField()
	Angkatan = models.IntegerField(choices=YEAR_CHOICES, default=datetime.datetime.now().year)
	Skill1 = models.TextField()
	Skill2 = models.TextField()
	Level1 = models.CharField(max_length=1, choices=LEVEL_CHOICES, default='1')
	Level2 = models.CharField(max_length=1, choices=LEVEL_CHOICES, default='1')
# Create your models here.
class Status(models.Model):
	message = models.CharField(max_length=100)
	created_date = models.DateTimeField(auto_now_add=True)

app_profile/forms.py
from django import forms
import datetime

LEVEL_CHOICES = (
	('',''),
	('Beginner','Beginner'),
	('Intermediate','Intermediate'),
	('Advanced','Advanced'),
	('Expert','Expert'),
	('Legend','Legend'),
)

class Friend_Form(forms.Form):
    NPM = forms.CharField(label='NPM', required=True, max_length=10)
    Nama = forms.CharField(label='Nama', required=True, )
    Angkatan =  forms.ChoiceField(choices=[(x, x) for x in range(1900, 2018)])
    Skill1 = forms.CharField(required=False)
    Skill2 = forms.CharField(required=False)
    Level1 = forms.ChoiceField(choices=LEVEL_CHOICES, required=False)
    Level2 = forms.ChoiceField(choices=LEVEL_CHOICES, required=False)
# Create your views here.
class Message_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, max_length=50)

app_profile/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import Friend_Form
from .models import Teman
from .riwayat_api import get_riwayat
from .forms import Message_Form
from .models import Status



response = {'author':'kelompok 13'}

def index(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('app:stats'))
    html = 'app_profile/session/login.html'
    return render(request, html, response)

def set_data_for_session(res, request):
    response['author'] = request.session['user_login']
    response['access_token'] = request.session['access_token']
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']
    response['friend_form'] = Friend_Form
    teman = Teman.objects.all()
    response['teman'] = teman 
    # response['mahasiswa'] =
    response['riwayats'] = get_riwayat()

    ## handling agar tidak error saat pertama kali login (session kosong)
    if 'drones' in request.session.keys():
        response['fav_drones'] = request.session['drones']
    # jika tidak ditambahkan else, cache akan tetap menyimpan data
    # sebelumnya yang ada pada response, sehingga data tidak up-to-date
    else:
        response['fav_drones'] = []

def stats(request):
    ## sol : bagaimana cara mencegah error, jika url profile langsung diakses
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('app:index'))

    set_data_for_session(response, request)
    status = Status.objects.all().order_by('-created_date')
    response['status'] = status
    response['message_form'] = Message_Form


    html = 'app_profile/session/stats.html'
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['NPM'] = request.POST['NPM']
        response['Nama'] = request.POST['Nama']
        response['Angkatan'] = request.POST['Angkatan']
        response['Skill1'] = request.POST['Skill1']
        response['Skill2'] = request.POST['Skill2']
        response['Level1'] = request.POST['Level1']
        response['Level2'] = request.POST['Level2']
        friend = Teman(NPM=response['NPM'], Nama=response['Nama'], Angkatan=response['Angkatan'], Skill1=response['Skill1'], Skill2=response['Skill2'], Level1=response['Level1'], Level2=response['Level2'])
        friend.save()
        return HttpResponseRedirect(reverse('app:index'))
    else:
        return HttpResponseRedirect(reverse('app:index'))

def add_status(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        status = Status(message=response['message'])
        status.save()
        html ='app_profile/session/stats.html'
        render(request, html, response)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/add_status/')

def database(request):
    name = request.POST['name']
    email = request.POST['email']
    profile_url = request.POST['profileUrl']
    image_url   = request.POST['imageUrl']

    request.user.profile.kode_identitas

    request.user.profile.update({
        'name': name,
        'image_url': image_url,
        'email': email,
        'profile_url': profile_url,
    })
    return JsonResponse({'save':'success'})

def edit_profile(request):
    html = 'app_profile/session/update_profile.html'
    return render(request, html, response)

app_profile/templates/app_profile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="TUGAS">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key: 81z52f0fcu4fkv
        authorize: true
        onLoad: onLinkedInLoad
        scope: r_basicprofile r_emailaddress
    </script>

    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Tugas By {{author}} {% endblock %}
    </title>
</head>
<body>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'js/app_profile.js' %}"></script>
</body>
</html>

app_profile/templates/app_profile/session/login.html
{% extends "app_profile/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'app:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_profile/templates/app_profile/session/stats.html
{% extends "app_profile/layout/base.html" %}
<!-- Content Here -->
<div class="pojok-kanan">

{% block content %}
<div class="container">
  {% if user_login %}
  <div class = "top">
    <div class="welcome">
      <h2> Selamat Datang, {{author}} </h2>
    </div>
    <div class = "prof-pict">
      <img class="cover" src="{{user_login.imageUrl}}" alt="3x4">
    </div>
  </div>
  {% endif %}
  <div class="button-section">
     <div class="forum-button">
       <div class="btn btn-warning">Lihat Forum</div>
     </div>
     <div class="edit-button">
       <a href="{% url 'app:edit_profile' %}" class="btn btn-primary">Edit Profile</a>
     </div>
     <div class="logout">
       <a href="{% url 'app:auth_logout' %}" class="btn btn-danger pull-right" onclick="return confirm('Keluar?')"> Logout </a>
     </div>
   </div>
 </div>

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active">
            <a href="#profile" aria-controls="settings" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#status" aria-controls="home" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'app_profile/tables/profile.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            <!-- Apply the same here -->
            {% include 'app_profile/tables/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="status">
            {% include 'app_profile/tables/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            {% include 'app_profile/tables/cari.html' %}
        </div>
    </div>
</div>
{% endblock %}

app_profile/templates/app_profile/session/update_profile.html
{% extends "app_profile/layout/base.html" %}
{% load static %}

{% block staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81z52f0fcu4fkv
    onLoad: onLinkedInLoad
    authorize: true
    lang: in_ID
</script>
{% endblock %}


{% block content %}
<div class="container">
  <div class="top">
    <div class="profile-picture">
      <img alt="3x4"/>
    </div>
    <div class="button-section">
      <div class="save-button">
        <div class="btn btn-primary" onclick=""> Simpan</div>
      </div>
      <div class="exit-button">
        <div class="btn btn-danger" onclick="logOut()">Keluar</div>
      </div>
    </div>
  </div>
  <div class="content">
    <script type="in/Login"></script>
  </div>
  <section class="lang-picker">
        <select class="my-select col-md-3" id="lang">
            <option></option>
        </select>
  </section>
  <section class="expertise-picker">
        <select class="my-select col-md-3" id="expertise">
            <option></option>
        </select>
  </section>
</div>
{% endblock %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script type="text/javascript" src="{% static 'js/app_profile.js' %}"></script>
<script type="text/javascript" src="{% static 'js/expertise.js' %}"></script>
{% endblock %}

app_profile/templates/app_profile/tables/cari.html
{% extends "app_profile/layout/base.html" %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
* {
box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 50%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
</head>

<h1 class="main-title">TODOLIST</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app:add_friend' %}">
            <h2>Input Friend</h2>
            {% csrf_token %}
            {{ friend_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>

<center>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for..." title="Type in a name">
</center>


<form>
    <center>
    <input type="radio" name="searchBy" value="NPM" id="r1" class="line1" checked> NPM<br>
    <input type="radio" name="searchBy" value="Nama" id="r2" class="line1"> Nama<br>
    <input type="radio" name="searchBy" value="Angkatan" id="r3" class="line1"> Angkatan<br>
    <input type="radio" name="searchBy" value="Keahlian" id="r4" class="line2"> Skill<br>
    <input type="radio" name="searchBy" value="Keahlian" id="r5" class="line2"> Level<br>
    </center>
</form> 
<!-- <section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My List</h2>
        <div class="flex">
            {% if teman %}
                {% for data in teman %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                {{data.NPM}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.Nama}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.Angkatan}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section> -->

<table id="myTable">
  <tr class="header">
    <th style="width:20%;"><center> NPM </center> </th>
    <th style="width:20%;"><center> Nama </center> </th>
    <th style="width:20%;"><center> Angkatan </center></th>
    <th style="width:20%;"><center> Skill </center></th>
    <th style="width:20%;"><center> Level </center></th>
  </tr>
    {% for data in teman %}
        <tr>
            <td>
              <center> {{ data.NPM }} </center>
            </td>

            <td>
              <center>{{ data.Nama }}</center>
            </td>

            <td>
              <center>{{ data.Angkatan }}</center>
            </td>

            <td>
              <center> {{ data.Skill1 }} </center>
              <div>

              </div>
              <center> {{ data.Skill2 }} </center>
            </td>

            <td> <center> {{ data.Level1 }} </center>
              <div>

              </div>
                <center> {{ data.Level2 }} </center>
            </td>
        </tr>
    {% endfor %}
</table>

<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  if (document.getElementById('r1').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[0];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

  if (document.getElementById('r2').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

  if (document.getElementById('r3').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[2];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

  if (document.getElementById('r4').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[3];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

  if (document.getElementById('r5').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[4];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

  if (document.getElementById('r6').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[5];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

  if (document.getElementById('r7').checked) {
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[6];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }

}
</script>

</html>
{% endblock %}        

app_profile/templates/app_profile/tables/profile.html
<section class="main-profile">
	<div class="container">
		<div class ="data">
      <table class ="table" style="font-size:20px">
        <tbody>

          {% if user_login %}
          <tr>
            <td><h2> Nama </h2></td>
            <td><h2> {{user_login.name}} </h2></td>
          </tr>
          <tr>
            <td><h2> NPM </h2></td>
            <td><h2> {{kode_identitas}} </h2></td>
          </tr>
          <tr>
            <td><h2> Keahlian </h2></td>
            <td><h2> Kosong </h2></td>
          </tr>
          <tr>
            <td><h2> Email </h2></td>
            <td><h2> {{user_login.email}} </h2></td>
          </tr>
          <tr>
            <td><h2> Profile Linkedin </h2></td>
            <td><h2> <a href="{{user.profileUrl}}"> {{user.profileUrl}} </h2></td>
          </tr>

          {% else %}
            <tr>
              <td><h2> Nama </h2></td>
              <td><h2> Kosong </h2></td>
            </tr>
            <tr>
              <td><h2> NPM </h2></td>
              <td><h2> {{kode_identitas}} </h2></td>
            </tr>
            <tr>
              <td><h2> Keahlian </h2></td>
              <td><h2> Kosong </h2></td>
            </tr>
            <tr>
              <td><h2> Email </h2></td>
              <td><h2> Kosong </h2></td>
            </tr>
            <tr>
              <td><h2> Profile Linkedin </h2></td>
              <td><h2> Kosong </h2></td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
	</div>
</section>

app_profile/templates/app_profile/tables/riwayat.html
<div class="panel panel-info">
	<div class="panel-body">
		<table class="table">
			<thead>
			    <tr>
			      <th>Mata Kuliah</th>
			      <th>Nilai</th>
		    	</tr>
		  	</thead>
			<tbody>
			{% for riwayat in riwayats %}
				<tr>
					<td>{{ riwayat.kelas.nm_mk_cl.nm_mk }}</td>
					<td>{{ riwayat.nilai }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>

app_profile/templates/app_profile/tables/status.html
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app:add_status' %}" >
            <h3>Update Status</h3>
            {% csrf_token %}
            {{ message_form }}
            <input type="submit" class="btn btn-primary pull-right" value="POST">
        </form>
    </div>
</section>

<section name = "my-status" id="my-status">
    {% for data in status %}
        <div class="flex-item" style="padding: 10px" id="statuses">
            <div  id = "time">
                <h4>{{ data.created_date }}</h4>
            </div>

            <div  id = "msg">
                <h4>{{data.message}}</h4>
            </div>


        </div>

        <div id="space">
            {{ " " }}
        </div>
    {% endfor %}
</section>